import { defineConfig } from "vite";
import laravel, { refreshPaths } from "laravel-vite-plugin";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                "resources/css/app.css",
                "resources/css/custom.css",
                "resources/js/app.js",
                "resources/js/embed.js",
                "resources/js/main.js",
                "resources/js/clipboard.js",
                "resources/views/templates/anniversary/enchanted-midnight-forest/css/style.css",
                "resources/views/templates/birthday/dark-blue-sequins/css/style.css",
                "resources/views/templates/anniversary/scarlet-serenity/css/style.css",
                "resources/views/templates/general/js/subscribe.js",
                "resources/views/templates/general/js/main.js",
                "resources/views/templates/meeting/punctual-meeting/css/style.css",
                "resources/views/templates/meeting/time-master/css/style.css",
                "resources/views/templates/study/shape-the-future/css/style.css",
                "resources/views/templates/live-stream/mind-body-wellness/css/style.css",
                "resources/views/templates/live-stream/science-experiment/css/style.css",
                "resources/views/templates/thanksgiving/feasting-around-the-corner/css/style.css",
                "resources/views/templates/vacation/great-escape/css/style.css",
                "resources/views/templates/fitness/peak-performance/css/style.css",
                "resources/views/templates/fitness/peak-performance-v2/css/style.css",
                "resources/views/templates/vacation/journey-to-relaxation/css/style.css",
                "resources/views/templates/vacation/dream-to-reality/css/style.css",
                "resources/views/templates/meeting/mastery-tracker/css/style.css",
                "resources/views/templates/meeting/time-keeper/css/style.css",
                "resources/views/templates/fitness/training-regimen/css/style.css",
                "resources/views/templates/new-year/ticking-away/css/style.css",
                "resources/views/templates/study/dare-to-start/css/style.css",
                "resources/views/templates/study/embracing-mastery/css/style.css",
                "resources/views/templates/study/mind-forge/css/style.css",
                "resources/views/templates/fitness/tailored-fitness-journey/css/style.css",
                "resources/views/templates/meeting/momentum-timer/css/style.css",
                "resources/views/templates/study/journey-to-mastery/css/style.css",
                "resources/views/templates/meeting/punctual-progress-timer/css/style.css",
                "resources/views/templates/vacation/sun-kissed-paradise/css/style.css",
                "resources/views/templates/vacation/adventure-escape/css/style.css",
                "resources/views/templates/study/quest-for-knowledge/css/style.css",
                "resources/views/templates/vacation/tranquil/css/style.css",
                "resources/views/templates/walk/step-by-step/css/style.css",
                "resources/views/templates/plant/watering-effortless/css/style.css",
                "resources/views/templates/birthday/ticking-time/css/style.css",
                "resources/views/templates/christmas/santa-s-spectacle/css/style.css",
                "resources/views/templates/birthday/building-excitement/css/style.css",
                "resources/views/templates/study/limitless-learning/css/style.css",
            ],
            refresh: [...refreshPaths, "app/Http/Livewire/**"],
        }),
    ],
});
